export const en = {
  "brand.name": "TenPrint Software",
  "brand.tagline": "Small, sharp software for macOS",

  "skip": "Skip to content",
  "nav.aria": "Primary",
  "nav.home": "Home",
  "nav.products": "Products",
  "nav.pricing": "Pricing",
  "nav.downloads": "Downloads",
  "nav.support": "Support",
  "nav.feedback": "Feedback",
  "nav.about": "About",
  "nav.menu": "Menu",
  "nav.close": "Close menu",
  "nav.allProducts": "All products",

  "theme.toggle": "Toggle theme",
  "language.label": "Language",
  "language.select": "Choose language",

  "cta.download": "Download",
  "cta.downloadFree": "Download free",
  "cta.buy": "Buy licence",
  "cta.explore": "Explore products",
  "cta.viewProduct": "View product",
  "cta.learnMore": "Learn more",
  "cta.getSupport": "Get support",
  "cta.sendFeedback": "Send feedback",
  "cta.productSite": "Product website",
  "cta.contactUs": "Contact us",

  "home.meta.title": "TenPrint Software — focused macOS utilities",
  "home.meta.description":
    "TenPrint Software builds small, fast macOS utilities that do one job well. Window management, session control, and more — free to download, one-time Pro licences, no analytics.",
  "home.hero.eyebrow": "Independent Mac software studio",
  "home.hero.title": "One line of code can draw an endless maze.",
  "home.hero.subtitle":
    "TenPrint Software builds small, fast macOS utilities that do one job properly and then get out of your way. Every app is free to download and free to keep using. Where an app has a Pro tier, you pay for it once.",
  "home.hero.note":
    "Every app runs entirely on your Mac and ships signed and notarised by Apple. Pro features are free to try for 14 days, and nothing you buy ever renews.",
  "home.hero.badge.native": "Native macOS",
  "home.hero.badge.privacy": "Privacy-first",
  "home.hero.badge.oneTime": "Pay once, never monthly",
  "home.hero.badge.notarised": "Signed & notarised",

  "home.products.title": "Our products",
  "home.products.subtitle":
    "Each app solves one real problem on the Mac. Pick the one you need — they work perfectly well on their own.",

  "home.principles.eyebrow": "Principles",
  "home.principles.title": "How we build",
  "home.principles.subtitle":
    "Four rules that decide what goes into a release, and what stays out.",
  "home.principles.one.title": "One job, done properly",
  "home.principles.one.text":
    "An app earns its place in the menu bar by solving a single problem completely. We would rather ship a small tool that never surprises you than a suite you have to learn.",
  "home.principles.two.title": "Your data stays on your Mac",
  "home.principles.two.text":
    "No accounts, no telemetry, no analytics pixels. Settings and layouts live in your own home folder, and the only network traffic is an update check and, for paid apps, a licence check.",
  "home.principles.three.title": "Buy once, keep it",
  "home.principles.three.text":
    "Paid apps use a one-time licence with a free trial first. No subscription, no feature that quietly disappears when a billing cycle ends.",
  "home.principles.four.title": "Honest release notes",
  "home.principles.four.text":
    "Every version ships with a changelog that says what actually changed, including the parts that are still in progress. Roadmaps are published, not implied.",

  "home.origin.eyebrow": "Where the name comes from",
  "home.origin.title": "10 PRINT",
  "home.origin.text":
    "On a Commodore 64, a single line of BASIC draws a maze that never repeats: 10 PRINT CHR$(205.5+RND(1)); : GOTO 10. Two diagonal characters, chosen at random, endlessly. It is the clearest demonstration we know that a very small program can produce something genuinely useful and genuinely surprising — which is exactly the kind of software we like to make.",
  "home.origin.caption": "The pattern behind this page is generated by that same rule.",

  "home.cta.title": "Try something today",
  "home.cta.subtitle":
    "Every app has a free download and a real trial. Install it, use it for a week, and decide afterwards.",

  "products.meta.title": "Products — TenPrint Software",
  "products.meta.description":
    "Browse every TenPrint Software app for macOS: SnappyZones window management and SessionGuard session control. Free downloads, one-time licences.",
  "products.title": "Products",
  "products.subtitle":
    "Small macOS utilities, each with its own site, its own release cycle, and its own free download.",
  "products.count": "{count} products",
  "products.more.title": "More on the way",
  "products.more.text":
    "New apps are added to this page as they ship. If you have an idea for a Mac utility that should exist, tell us about it.",

  "product.badge.free": "Free",
  "product.badge.pro": "Pro",
  "product.badge.freemium": "Free with optional Pro",
  "product.badge.paid": "Paid",
  "product.platform": "Platform",
  "product.category": "Category",
  "product.version": "Latest version",
  "product.licence": "Licence",
  "product.status": "Status",
  "product.status.stable": "Stable",
  "product.status.beta": "Beta",
  "product.overview": "Overview",
  "product.features.default": "Features",
  "product.how.default": "How it works",
  "product.quickStart.default": "Quick start",
  "product.roadmap.default": "Roadmap",
  "product.faq": "Frequently asked questions",
  "product.download.title": "Download {name}",
  "product.download.subtitle": "Get the latest build for macOS, straight from the product site.",
  "product.download.requirements": "Requires {requirements}",
  "product.pricing.title": "Pricing",
  "product.pricing.free.title": "Free",
  "product.pricing.free.price": "€0",
  "product.pricing.free.note": "Free to use, including in a business.",
  "product.pricing.pro.note": "One-time payment. No subscription.",
  "product.support.title": "Need a hand?",
  "product.support.text":
    "Installation trouble, a permission that will not stick, or a bug worth reporting — we answer every message ourselves.",
  "product.related.title": "Other products",
  "product.roadmap.inProgress": "In development",
  "product.roadmap.planned": "Planned",

  "pricing.meta.title": "Pricing — TenPrint Software",
  "pricing.meta.description":
    "Simple pricing for TenPrint Software apps: free downloads, one-time Pro licences, no subscriptions. VAT handled by our merchant of record.",
  "pricing.title": "Pricing",
  "pricing.subtitle":
    "Every app is free to download and free to try. Where there is a Pro tier, it is a one-time payment — never a subscription.",
  "pricing.perLifetime": "one-time",
  "pricing.included": "What you get",
  "pricing.free.title": "Free",
  "pricing.free.subtitle": "The core of every app, with no time limit.",
  "pricing.pro.subtitle": "Everything in Free, plus the power-user features.",
  "pricing.notice.vat": "Prices exclude VAT where applicable. VAT is calculated at checkout.",
  "pricing.notice.mor":
    "Payments are handled by our merchant of record, who issues your invoice and handles VAT reporting.",
  "pricing.faq.title": "Buying and licences",
  "pricing.faq.q1": "Do I need an account?",
  "pricing.faq.a1":
    "No. After checkout you receive a licence key by email. You paste it into the app and that is the whole process — there is no TenPrint account to create, and no login inside the apps.",
  "pricing.faq.q2": "How many Macs does a licence cover?",
  "pricing.faq.a2":
    "A personal licence covers two Macs that you use yourself — for example a desktop and a laptop. If you need more seats for a team, write to us and we will sort out a volume licence.",
  "pricing.faq.q3": "Is there a trial?",
  "pricing.faq.a3":
    "Yes. Pro features run for 14 days without a licence key, with nothing disabled during the trial. When the trial ends the app keeps working — you simply drop back to the free feature set.",
  "pricing.faq.q4": "What happens with future versions?",
  "pricing.faq.a4":
    "A licence is perpetual for the major version you bought, and every update within that version is included. If a future major version ever carries a paid upgrade, existing customers get a discount.",
  "pricing.faq.q5": "Can I get a refund?",
  "pricing.faq.a5":
    "Yes — within 30 days of purchase, for any reason, no questions asked. Email us with your order number and we will refund it.",
  "pricing.faq.q6": "Do you invoice businesses?",
  "pricing.faq.a6":
    "Yes. Enter your company name and VAT number at checkout and you will receive a proper VAT invoice. EU business customers are handled under the reverse-charge mechanism.",

  "category.windowing": "Window management",
  "category.session": "Session control",

  "pricing.snappyzones.free.1": "Drag-and-drop snapping with the zone overlay",
  "pricing.snappyzones.free.2": "One custom layout per display, built in the Zone Editor",
  "pricing.snappyzones.free.3": "Grid presets, multi-monitor support, keyboard shortcuts",
  "pricing.snappyzones.free.4": "Automatic updates, for free, forever",
  "pricing.snappyzones.pro.1": "Unlimited named layouts on every display",
  "pricing.snappyzones.pro.2": "Switch Layout picker, plus next and previous layout shortcuts",
  "pricing.snappyzones.pro.3": "Move the front window to the next display",
  "pricing.snappyzones.pro.4": "Backup and restore layouts and preferences as JSON",
  "pricing.snappyzones.pro.5": "Licence for two Macs, 14-day trial, no account needed",
  "pricing.sessionguard.free.1": "Keep a login session alive with 1-pixel micro-movements",
  "pricing.sessionguard.free.2": "Timed sessions from 15 minutes to 8 hours",
  "pricing.sessionguard.free.3": "Adjustable idle threshold and jiggle interval",
  "pricing.sessionguard.free.4": "Free for personal and commercial use",
  "pricing.walkaway.free.1": "Lock the screen when you walk away — jobs keep running",
  "pricing.walkaway.free.2": "One trusted Bluetooth device — Watch, iPhone, or any BLE device",
  "pricing.walkaway.free.3": "Away delay and RSSI threshold you control",
  "pricing.walkaway.free.4": "Free for personal and commercial use",

  "downloads.meta.title": "Downloads — TenPrint Software",
  "downloads.meta.description":
    "Download the latest macOS builds of every TenPrint Software app. Signed, notarised disk images, straight from the product sites.",
  "downloads.title": "Downloads",
  "downloads.subtitle":
    "The latest signed build of every app. Downloads are served from each product's own site, so you always get the current release.",
  "downloads.notice.title": "Installing on macOS",
  "downloads.notice.step1": "Open the downloaded disk image.",
  "downloads.notice.step2": "Drag the app into your Applications folder.",
  "downloads.notice.step3": "Launch it from Applications, then grant the permissions it asks for.",
  "downloads.notice.gatekeeper":
    "Our builds are signed with an Apple Developer ID and notarised by Apple, so Gatekeeper opens them without you having to change any security settings.",

  "support.meta.title": "Support — TenPrint Software",
  "support.meta.description":
    "Get help with a TenPrint Software app. Read the product FAQs, check known issues, or send us a message — every request is answered by a human.",
  "support.title": "Support",
  "support.subtitle":
    "Something not working? Tell us what you are seeing and we will help. Every message goes to the people who wrote the code.",
  "support.channels.title": "Before you write",
  "support.channels.faq.title": "Check the product FAQ",
  "support.channels.faq.text":
    "Permission prompts, updates, and licence questions are answered on each product page. It is the fastest route to an answer.",
  "support.channels.update.title": "Make sure you are current",
  "support.channels.update.text":
    "Run Check for Updates… inside the app, or download the latest build. A surprising number of reports are already fixed in the current release.",
  "support.channels.details.title": "Send us the details",
  "support.channels.details.text":
    "Your macOS version, the app version, and what you did just before the problem appeared. That is usually enough for us to reproduce it.",
  "support.response.title": "Response time",
  "support.response.text":
    "We aim to reply within two working days. TenPrint Software is a small studio, so answers come from a person, not a queue.",

  "feedback.meta.title": "Feedback — TenPrint Software",
  "feedback.meta.description":
    "Tell TenPrint Software what to build next. Feature requests, rough edges, and honest criticism are all welcome.",
  "feedback.title": "Feedback",
  "feedback.subtitle":
    "Feature requests, rough edges, things that annoy you — this is where roadmaps come from. Say it plainly; we would rather hear it.",
  "feedback.promise.title": "What happens to your message",
  "feedback.promise.text":
    "Every piece of feedback is read and filed against a product. If an idea makes it into a release, it appears in the changelog and on the product roadmap.",

  "form.name": "Name",
  "form.email": "Email",
  "form.emailHint": "So we can reply. We never add you to a mailing list.",
  "form.product": "Product",
  "form.product.general": "General question",
  "form.topic": "Topic",
  "form.topic.support": "I need help with something",
  "form.topic.bug": "I found a bug",
  "form.topic.feature": "I have a feature request",
  "form.topic.purchase": "Purchase, licence, or invoice",
  "form.topic.other": "Something else",
  "form.system": "macOS and app version",
  "form.systemHint": "For example: macOS 15.2, SnappyZones 1.3.2",
  "form.message": "Message",
  "form.send": "Send message",
  "form.sending": "Sending…",
  "form.required": "Required",
  "form.optional": "Optional",
  "form.success.title": "Message sent",
  "form.success.text": "Thank you. We read every message and reply within two working days.",
  "form.error.title": "That did not go through",
  "form.error.text":
    "Something went wrong on our side. Please try again, or email us directly at {email}.",
  "form.error.validation": "Please fill in your email address and a message.",
  "form.privacy":
    "We use your message and email address only to answer you. Nothing is shared with anyone else.",
  "form.orEmail": "Or write to us directly:",

  "about.meta.title": "About — TenPrint Software",
  "about.meta.description":
    "TenPrint Software is an independent studio building small, privacy-respecting macOS utilities. Here is how we work and what we believe.",
  "about.title": "About TenPrint Software",
  "about.subtitle":
    "An independent studio making the sort of Mac utilities we wanted to use ourselves.",
  "about.story.title": "The short version",
  "about.story.p1":
    "TenPrint Software started with a simple frustration: the small things a Mac does not do well enough. Arranging windows the same way every morning. Keeping a session alive through a long call. Each problem was small enough to fix in an afternoon and annoying enough to be worth fixing properly.",
  "about.story.p2":
    "So each one became an app. Small, native, and focused — the sort of tool you install once, configure in five minutes, and then forget about because it simply works. That is the whole ambition. We are not trying to build a platform.",
  "about.story.p3":
    "Everything is written for macOS specifically, tested on current hardware, signed with an Apple Developer ID, and notarised by Apple. When a release is not ready, it does not ship.",

  "about.values.title": "What we will not do",
  "about.values.one.title": "No accounts",
  "about.values.one.text":
    "You do not sign up to use our software. A licence key is a string you paste in, not an identity we store.",
  "about.values.two.title": "No tracking",
  "about.values.two.text":
    "No analytics in the apps, no third-party scripts on this site, no cookie banner because there is nothing to consent to.",
  "about.values.three.title": "No dark patterns",
  "about.values.three.text":
    "No countdown timers, no fake discounts, no nagging dialogs. The trial ends quietly and the app keeps working.",
  "about.values.four.title": "No abandoned apps",
  "about.values.four.text":
    "If we ever stop developing something, we will say so clearly and release the last build as free software rather than let it rot.",

  "about.contact.title": "Get in touch",
  "about.contact.text":
    "Questions about a product, a licence, press, or a partnership — the same inbox handles all of it.",

  "legal.meta.privacy": "Privacy policy — TenPrint Software",
  "legal.meta.terms": "Terms of service — TenPrint Software",
  "legal.meta.refund": "Refund policy — TenPrint Software",
  "legal.privacy": "Privacy policy",
  "legal.terms": "Terms of service",
  "legal.refund": "Refund policy",
  "legal.imprint": "Imprint",
  "legal.updated": "Last updated: {date}",
  "legal.englishOnly":
    "This document is published in English only. If anything is unclear, write to us and we will explain it in your language.",

  "footer.products": "Products",
  "footer.company": "Company",
  "footer.legal": "Legal",
  "footer.help": "Help",
  "footer.rights": "All rights reserved.",
  "footer.built": "Designed and built in Hungary for macOS.",
  "footer.email": "Email us",

  "notFound.title": "This page does not exist",
  "notFound.subtitle":
    "The link may be out of date, or the page may have moved. Try the products page — everything is one click from there.",
  "notFound.cta": "Go to products",
} as const;

export type UiKey = keyof typeof en;
